### ISSUE TITLE
trait `fitsio::images::ReadImage` is not implemented for `ndarray...`

### ISSUE THREAD

**Issue by Findus23** [mindriot101/rust-fitsio#102]
Hi,

Sorry, if I am making an obvious mistake as I am a total rust beginner.

Everything seems to be working fine until I want to create an ndarray from the image in the FITS file. 

No matter how I write it, I always get an 
>the trait bound `ndarray::ArrayBase<ndarray::OwnedRepr<u32>, ndarray::dimension::dim::Dim<ndarray::dimension::dynindeximpl::IxDynImpl>>: fitsio::images::ReadImage` is not satisfied 

error.

I think this is not just caused by my code as I can reproduce it by trying to compile the example code in this repo:

```
➜  ~/tmp git clone git@github.com:mindriot101/rust-fitsio.git
Klone nach 'rust-fitsio' ...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 5665 (delta 65), reused 88 (delta 46), pack-reused 5544
Empfange Objekte: 100% (5665/5665), 6.85 MiB | 2.05 MiB/s, Fertig.
Löse Unterschiede auf: 100% (4305/4305), Fertig.
➜  ~/tmp cd rust-fitsio/homepage/fitsioexample 
➜  ~/…/homepage/fitsioexample git:(master) cargo run --bin ndarray_support
    Updating git repository `https://github.com/mindriot101/rust-fitsio`
    Updating crates.io index
   Compiling num-traits v0.2.6
   Compiling matrixmultiply v0.1.15
   Compiling libc v0.2.51
   Compiling pkg-config v0.3.14
   Compiling either v1.5.1
   Compiling num-complex v0.2.1
   Compiling rawpointer v0.1.0
   Compiling ndarray v0.11.2
   Compiling ndarray v0.12.1
   Compiling itertools v0.7.11
   Compiling fitsio-sys v0.3.0 (https://github.com/mindriot101/rust-fitsio#98910ee3)
   Compiling num-traits v0.1.43
   Compiling num-complex v0.1.43
   Compiling fitsio v0.14.1 (https://github.com/mindriot101/rust-fitsio#98910ee3)
   Compiling fitsioexample v0.1.0 (/home/lukas/tmp/rust-fitsio/homepage/fitsioexample)
error[E0277]: the trait bound `ndarray::ArrayBase<ndarray::OwnedRepr<f32>, ndarray::Dim<ndarray::IxDynImpl>>: fitsio::images::ReadImage` is not satisfied
  --> src/bin/ndarray_support.rs:12:31
   |
12 | let image: ArrayD<f32> = phdu.read_image(&mut fptr)?;
   |                               ^^^^^^^^^^ the trait `fitsio::images::ReadImage` is not implemented for `ndarray::ArrayBase<ndarray::OwnedRepr<f32>, ndarray::Dim<ndarray::IxDynImpl>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `fitsioexample`.

To learn more, run the command again with --verbose.
```

Maybe it isn't working because I seem to be using the latest rust version:

```
➜ cargo --version
cargo 1.33.0 (f099fe94b 2019-02-12)
➜ rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by mindriot101** [comment]
Hi, thanks for the interest in my fits library and rust.

I'm not at my computer right now, but can I ask if you're saying the
`array` feature to your cargo.toml?

E.g. see this:
https://github.com/mindriot101/rust-fitsio/blob/master/homepage/fitsioexample/Cargo.toml

Thanks

**Comment by Findus23** [comment]
As I am also getting the when cloning this repo with the Cargo.toml you linked to (see above), I don't think this is the issue.

**Comment by mindriot101** [comment]
Hi @Findus23, can you try a fresh clone of branch `readimage-not-implemented-for-ndarray`:

```sh
git clone https://github.com/mindriot101/rust-fitsio
cd rust-fitsio
git checkout readimage-not-implemented-for-ndarray
cd homepage/fitsioexample
cargo build --bin ndarray_support
```

I've pushed a new PR (#103), and as far as I can tell the explanation for the problem is to do with trait implementations being linked to structs from different code versions i.e. structs in different versions of crates are treated as different structs.

**Comment by Findus23** [comment]
Hi, 
you are right, the new branch compiles.

I just didn't pay attention and simply installed the latest `ndarray`.

**Comment by mindriot101** [comment]
That's ok, it surprised me too! Thanks for pointing this out, and help me
improve the crate.

I'll merge the pr now
